# version: "3.8"

services:
  # GPT-SoVITS-CU126:
  #   image: xxxxrt666/gpt-sovits:latest-cu126
  #   container_name: GPT-SoVITS-CU126
  #   ports:
  #     - "8000:8000"
  #     - "9871:9871"
  #     - "9872:9872"
  #     - "9873:9873"
  #     - "9874:9874"
  #     - "9880:9880"
  #   volumes:
  #     - .:/workspace/GPT-SoVITS
  #   environment:
  #     - is_half=true
  #   tty: true
  #   stdin_open: true
  #   shm_size: "16g"
  #   restart: unless-stopped
  #   # runtime: nvidia
  #   command: python gsvi.py -p 8000   # <== 新增此行，容器直接启动此 WebUI
  #   device_requests:
  #     - driver: "nvidia"
  #       count: -1
  #       capabilities: ["gpu"]
  # GPT-SoVITS-CU126-Lite:
  #   image: xxxxrt666/gpt-sovits:latest-cu126-lite
  #   container_name: GPT-SoVITS-CU126-Lite
  #   ports:
  #     - "8000:8000"
  #     - "9871:9871"
  #     - "9872:9872"
  #     - "9873:9873"
  #     - "9874:9874"
  #     - "9880:9880"
  #   volumes:
  #     - .:/workspace/GPT-SoVITS
  #     - .:/tools/asr/models:/workspace/models/asr_models
  #     - .:/tools/uvr5/uvr5_weights:/workspace/models/uvr5_weights
  #   environment:
  #     - is_half=true
  #   tty: true
  #   stdin_open: true
  #   shm_size: "16g"
  #   restart: unless-stopped
  #   # runtime: nvidia
  #   command: python gsvi.py -p 8000   # <== 新增此行，容器直接启动此 WebUI
  #   device_requests:
  #     - driver: "nvidia"
  #       count: -1
  #       capabilities: ["gpu"]
  GPT-SoVITS-CU128:
    image: xxxxrt666/gpt-sovits:latest-cu128
    container_name: GPT-SoVITS-CU128
    ports:
      - "8000:8000"
      - "9871:9871"
      - "9872:9872"
      - "9873:9873"
      - "9874:9874"
      - "9880:9880"
    volumes:
      - .:/workspace/GPT-SoVITS
    environment:
      - is_half=true
    tty: true
    stdin_open: true
    shm_size: "16g"
    restart: unless-stopped
    runtime: nvidia
    command: python gsvi.py -p 8000   # <== 新增此行，容器直接启动此 WebUI
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all  # 或者指定数量，如 1
    #           capabilities: [gpu]
  # GPT-SoVITS-CU128-Lite:
  #   image: xxxxrt666/gpt-sovits:latest-cu128-lite
  #   container_name: GPT-SoVITS-CU128-Lite
  #   ports:
  #     - "8000:8000"
  #     - "9871:9871"
  #     - "9872:9872"
  #     - "9873:9873"
  #     - "9874:9874"
  #     - "9880:9880"
  #   volumes:
  #     - .:/workspace/GPT-SoVITS
  #     - .:/tools/asr/models:/workspace/models/asr_models
  #     - .:/tools/uvr5/uvr5_weights:/workspace/models/uvr5_weights
  #   environment:
  #     - is_half=true
  #   tty: true
  #   stdin_open: true
  #   shm_size: "16g"
  #   restart: unless-stopped
  #   # runtime: nvidia
  #   command: python gsvi.py -p 8000   # <== 新增此行，容器直接启动此 WebUI
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]